version: '3.8'

# Development service
services:
  app-dev:
    container_name: api-bots-discord-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on:
      - db  
    profiles:
      - dev    

# Production service
  app-prod:
    container_name: api-bots-discord-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "9015"
    environment:
      - PORT=9015
    depends_on:
      - db  
    networks:
      - app-network
    profiles:
      - prod

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: api-bots-discord-nginx
    ports:
      - "80:9015"
    environment:
      - NGINX_PORT=80
      - NGINX_PROXY_PASS=http://app-prod:9015
    command: /bin/sh -c "nginx -g 'daemon off;' & \
             echo 'server { \
             listen ${NGINX_PORT}; \
             location / { \
                 proxy_pass ${NGINX_PROXY_PASS}; \
                 proxy_http_version 1.1; \
                 proxy_set_header Upgrade $$http_upgrade; \
                 proxy_set_header Connection \"upgrade\"; \
                 proxy_set_header Host $$host; \
                 proxy_cache_bypass $$http_upgrade; \
             } \
             }' > /etc/nginx/conf.d/default.conf && \
             nginx -s reload && \
             wait"
    depends_on:
      - app-prod
    networks:
      - app-network
    profiles:
      - prod

# Database service (PostgreSQL)
  db:
    image: postgres:17-alpine
    container_name: api-bots-discord-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-bots-discord
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

# pgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: api-bots-discord-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

# Volumes definition
volumes:
  pgdata:

# Networks definition
networks:
  app-network:
    driver: bridge
