# Use a lightweight Node.js image compatible with multi-architecture
FROM --platform=$BUILDPLATFORM node:22-alpine as development

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start:dev"]