# Use a lightweight Node.js image compatible with multi-architecture
FROM --platform=$BUILDPLATFORM node:22-alpine as build

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Use a lightweight Node.js image compatible with multi-architecture
FROM --platform=$BUILDPLATFORM node:22-alpine as production

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package*.json ./

# Expose the application port   
EXPOSE 3000

# Command to run the application
CMD [ "npm", "run", "start:prod" ]